### PR TITLE
Added support for 14.x 

### PR DESCRIPTION
**Pull request by marcoantoni0**
Just a new line to support node 14.x runtime

### CODE REVIEW

**Comment by matt-filion** [comment]
Bump. We would like to use node14 and this is a hard block.

**Comment by mohitagrwl07** [comment]
We have upgraded the node version to node14 so require this change to be merged.

**Comment by strandedmusician** [comment]
We are also facing the same issue in an upgrade to the node14 runtime for our Lambda functions.

**Comment by marcoantoni0** [comment]
> Bump. We would like to use node14 and this is a hard block.
@matt-filion 


Yes, it was a problem for me too 😞 
I made a patch-package to fix it temporarily.

Anyway, the lib doesn't seems to be being maintained.

**Comment by matt-filion** [comment]
This has happened before. I wouldn't say this project is abandoned, but it certainly ahs entered a state of stable, and doesnt get frequent attention. I think we found some emails before to some of the repo maintainers, will try to ping those.

@diogogvhenriques Are you able to help out in getting this merged?

**Comment by diogogvhenriques** [comment]
Thanks for the help @marcoantoni0 and @matt-filion for pinging me.
We have been having a lot on our plate and has been hard to keep up with the update of the package.

**Pull request merged**
