### PR TITLE
added support for nodejs12.x

### PR DESCRIPTION
**Pull request by dkhunt27**

### CODE REVIEW

**Comment by matt-filion** [comment]
We are updating to node12.x and would like to see this merged in to avoid having to do a lot of extra work for our builds. 

Thanks!

**Comment by matt-filion** [comment]
How come this is still idle?

**Comment by jonasduever** [comment]
Had to hack this fix into my dependencies for now. Would be nice if it gets merged and published soon :)

**Comment by mjmitchell86** [comment]
Hi!  Is there an ETA for when you think this may be merged into master?  We are also hacking this into our current serverless applications and would be nice to have it more easily available.

**Comment by adriangmweb** [comment]
Any estimations on this?

Just migrated Serverless to node 12.x due to now it's LTS, and it would be nice to be able to use the plugin.

**Comment by jonasduever** [comment]
So..who could merge this?
Maybe @diogogvhenriques @goncaloneves ? (Sorry if you aren't active/responsible anymore, just looked at the last commits.)

**Comment by diogogvhenriques** [comment]
Thanks @dkhunt27 for the PR

**Pull request merged**
